### ISSUE TITLE
Push newly build images to local registry instead of just leaving in cache

### ISSUE THREAD

**Issue by Nathan-Hausman** [capstone-kubernetes-aas/build-service#6]
The local registry is located at `localhost:5000`, but the pipeline doesn't need to know this as the website will add it to the image name in the deployment config. All that is needed is an additional line implementing the `docker push <image-name>` command.

**Comment by Nathan-Hausman** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GHP: Push image to local registry](https://trello.com/c/oGFw1Ufu/44-ghp-push-image-to-local-registry)

**Comment by detjensrobert** [comment]
Waiting on #5 to be merged first so less rebasing
